http:
 listener:
  host: "localhost"
  port: "8085"
 requester:
  TravelOnTip:
    host: "localhost"
    port: "8083"
    routesPath: "/TravelOnTip/routes"
    schedulesPath: "/TravelOnTip/Schedule"
  FastGo:
    host: "localhost"
    port: "8084"
    routesPath: "/FastGo/routes"
    schedulesPath: "/FastGo/schedules"

